name: sra2variant
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - sra-tools>=2.11.0
  - trimmomatic
  - fastp=0.20.1
  - bwa=0.7.17
  - bowtie2
  - hisat2
  - picard=2.18.2
  - lofreq=2.1.5
  - bcftools
  - python>=3.7
  - pip
  - pyvcf
  - pysam
  - numpy
  - git
  - pip:
    - git+https://github.com/wuaipinglab/sra2variant.git
