name: sra2variant
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - sra-tools>=2.11.0
  - trimmomatic
  - fastp
  - bwa
  - bowtie2
  - hisat2
  - picard
  - lofreq
  - bcftools
  - python>=3.7
  - pip
  - pyvcf
  - pysam
  - numpy
  - git
  - pip:
    - git+https://github.com/wuaipinglab/sra2variant.git
