name: sra2variant
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - sra-tools
  - trimmomatic
  - fastp
  - bwa
  - picard
  - ivar
  - vcflib
  - lofreq
  - python>=3.7
  - pip
  - pyvcf
  - git
  - pip:
    - git+https://gitee.com/wuaipinglab/sra2variant.git
