name: sra2variant
on: [push, pull_request]
defaults:
  run:
    shell: bash -l {0}

jobs:
  run_sra2variant_test:
    name: sra2variant test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: sra2variant
          channels: conda-forge,bioconda,defaults
      - name: Install sra2variant
        run: pip install -e .
      - name: Test with unittest
        run: |
          python ./tests/test_workflow.py
